name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Executar scan de segurança diariamente às 2:00 UTC
    - cron: '0 2 * * *'

# Configurar permissões específicas para segurança
permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          
      - name: Check if main scan file exists
        id: check-main
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.check-main.outputs.exists == 'true'
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'Trivy Security Scan'
          checkout_path: ${{ github.workspace }}

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: projeto-hamburgueria/package-lock.json
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Run Trivy dependency scan (Node.js)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'projeto-hamburgueria'
          format: 'sarif'
          output: 'trivy-deps-nodejs.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          
      - name: Run Trivy dependency scan (Go)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'backend-hamburgueria'
          format: 'sarif'
          output: 'trivy-deps-go.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          
      - name: Check if Node.js scan file exists
        id: check-nodejs
        run: |
          if [ -f "trivy-deps-nodejs.sarif" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Check if Go scan file exists
        id: check-go
        run: |
          if [ -f "trivy-deps-go.sarif" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload Node.js dependency scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.check-nodejs.outputs.exists == 'true'
        with:
          sarif_file: 'trivy-deps-nodejs.sarif'
          category: 'Trivy Dependency Scan (Node.js)'
          
      - name: Upload Go dependency scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.check-go.outputs.exists == 'true'
        with:
          sarif_file: 'trivy-deps-go.sarif'
          category: 'Trivy Dependency Scan (Go)' 