name: Security Scan (Simple)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Executar scan de segurança diariamente às 2:00 UTC
    - cron: '0 2 * * *'

# Configurar permissões específicas para segurança
permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          
      - name: Check if scan file exists
        id: check-scan
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "File size: $(wc -c < trivy-results.sarif) bytes"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Scan file not found"
          fi
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.check-scan.outputs.exists == 'true'
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'Trivy Security Scan'
          checkout_path: ${{ github.workspace }}
          
      - name: Show scan results summary
        if: always()
        run: |
          echo "=== Security Scan Summary ==="
          echo "Scan file exists: ${{ steps.check-scan.outputs.exists }}"
          if [ -f "trivy-results.sarif" ]; then
            echo "Scan completed successfully"
            echo "File size: $(wc -c < trivy-results.sarif) bytes"
          else
            echo "Scan failed or file not generated"
          fi 